"""fix product

Revision ID: 0919de7e0883
Revises: c3a31fa293bc
Create Date: 2024-05-31 02:34:03.041811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0919de7e0883'
down_revision: Union[str, None] = 'c3a31fa293bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'rating')
    op.drop_column('product', 'photo')
    op.drop_constraint('user_x_product_club_id_fkey', 'user_x_product', type_='foreignkey')
    op.drop_column('user_x_product', 'club_id')
    op.drop_column('user_x_product', 'date')
    op.drop_column('user_x_product', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_x_product', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_x_product', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user_x_product', sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_x_product_club_id_fkey', 'user_x_product', 'club', ['club_id'], ['id'])
    op.add_column('product', sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###