"""db creation

Revision ID: 2af263bb6230
Revises: 9f4ba8d24daa
Create Date: 2024-05-21 17:35:23.869010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af263bb6230'
down_revision: Union[str, None] = '9f4ba8d24daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('uid', sa.String(length=255), nullable=False))
    op.add_column('club_x_user', sa.Column('is_main', sa.Boolean(), nullable=False))
    op.add_column('event', sa.Column('reward', sa.Integer(), nullable=False))
    op.add_column('event_reg', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('event_reg', sa.Column('was', sa.Boolean(), nullable=False))
    op.drop_column('event_reg', 'confirm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_reg', sa.Column('confirm', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('event_reg', 'was')
    op.drop_column('event_reg', 'status')
    op.drop_column('event', 'reward')
    op.drop_column('club_x_user', 'is_main')
    op.drop_column('club', 'uid')
    # ### end Alembic commands ###
