"""db creation

Revision ID: b465247ddcbd
Revises: ec7b4931d835
Create Date: 2024-03-23 00:33:26.741027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b465247ddcbd'
down_revision: Union[str, None] = 'ec7b4931d835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('xp', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(), nullable=False))
    op.add_column('user', sa.Column('education', sa.String(), nullable=False))
    op.add_column('user', sa.Column('achievments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'achievments')
    op.drop_column('user', 'education')
    op.drop_column('user', 'city')
    op.drop_column('user', 'xp')
    # ### end Alembic commands ###
