"""db creation

Revision ID: f152506022f6
Revises: 86e22e0089cf
Create Date: 2024-03-27 02:07:52.928539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f152506022f6'
down_revision: Union[str, None] = '86e22e0089cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('channel_link', sa.String(length=255), nullable=False))
    op.add_column('club_x_user', sa.Column('balance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_x_user', 'balance')
    op.drop_column('club', 'channel_link')
    # ### end Alembic commands ###
